services:
  - type: web
    name: bungalov-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:push && npm run prisma:seed && npm run start:prod
    healthCheckPath: /api/bungalows
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20.18.1"
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://frontend-blush-three-90.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bungalov-db
          property: connectionString

databases:
  - name: bungalov-db
    plan: free
